import a from './../images/1.jpeg'
import b from './../images/2.jpeg'
import c from './../images/3.jpeg'
import d from './../images/4.jpeg'
import e from './../images/5.jpeg'
import f from './../images/6.jpeg'
import g from './../images/7.jpeg'
import h from './../images/8.jpeg'
import i from './../images/9.jpeg'
import j from './../images/10.jpeg'
import k from './../images/11.jpeg'
import l from './../images/12.jpeg'
import m from './../images/13.jpeg'
import n from './../images/14.jpeg'
import o from './../images/15.jpeg'
import p from './../images/16.jpeg'
import q from './../images/17.jpeg'
import r from './../images/18.jpeg'
import s from './../images/19.jpeg'
import t from './../images/20.jpeg'
import u from './../images/21.jpeg'
import v from './../images/22.jpeg'
import w from './../images/23.jpeg'
import x from './../images/24.jpeg'
import y from './../images/25.jpeg'
import z from './../images/26.jpeg'
import aa from './../images/27.jpeg'
import ab from './../images/28.jpeg'
import ac from './../images/29.jpeg'
import ad from './../images/30.jpeg'
import ae from './../images/31.jpeg';
import af from './../images/32.jpeg'
import ag from './../images/33.jpeg'
import ah from './../images/34.jpeg'
import ai from './../images/35.jpeg'
import aj from './../images/36.jpeg'
import ak from './../images/37.jpeg'
import al from './../images/38.jpeg'
import am from './../images/39.jpeg'
import an from './../images/40.jpeg'
import ao from './../images/41.jpeg'
import ap from './../images/42.jpeg'
import aq from './../images/43.jpeg'
import ar from './../images/44.jpeg'
import as from './../images/45.jpeg'
import at from './../images/46.jpeg'
import au from './../images/47.jpeg'
import av from './../images/48.jpeg'
import aw from './../images/49.jpeg'
import ax from './../images/50.jpeg'
import ay from './../images/51.jpeg'
import az from './../images/52.jpeg'
import ba from './../images/53.jpeg'
import bb from './../images/54.jpeg'
import bc from './../images/55.jpeg'
import bd from './../images/56.jpeg'
import be from './../images/57.jpeg'
import bf from './../images/58.jpeg'
import bg from './../images/59.jpeg'
import bh from './../images/60.jpeg'
import bi from './../images/61.jpeg'
import bj from './../images/62.jpeg'
import bk from './../images/63.jpeg'
import bl from './../images/64.jpeg'
import bm from './../images/65.jpeg'
import bn from './../images/66.jpeg'
import bo from './../images/67.jpeg'
import bp from './../images/68.jpeg'
import bq from './../images/69.jpeg'
import br from './../images/70.jpeg'
import bs from './../images/71.jpeg'
import bt from './../images/72.jpeg'
import bu from './../images/73.jpeg'
import bv from './../images/74.jpeg'
import bw from './../images/75.jpeg'
import bx from './../images/76.jpeg'
import by from './../images/77.jpeg'
import bz from './../images/78.jpeg'
import ca from './../images/79.jpeg'
import cb from './../images/80.jpeg'
import cc from './../images/81.jpeg'
import cd from './../images/82.jpeg'
import ce from './../images/83.jpeg'
import cf from './../images/84.jpeg'
import cg from './../images/85.jpeg'
import ch from './../images/86.jpeg'
import ci from './../images/87.jpeg'
import cj from './../images/88.jpeg'
import ck from './../images/89.jpeg'
import cl from './../images/90.jpeg'
import cm from './../images/91.jpeg'
import cn from './../images/92.jpeg'
import co from './../images/93.jpeg'
import cp from './../images/94.jpeg'
import cq from './../images/95.jpeg'
import cr from './../images/96.jpeg'
import cs from './../images/97.jpeg'
import ct from './../images/98.jpeg'
import cu from './../images/99.jpeg'
import cv from './../images/100.jpeg'

const CarsData = [
  {
    id: 1,
    name: 'Audi A3',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 400,
    automatic: true,
    price: 25000,
    imageUrl: a,
    carType: 'Sedan'
  },
  {
    id: 2,
    name: 'BMW X5',
    yearProduced: 2023,
    occupants: 4,
    hybrid: true,
    distanceOnFullTank: 500,
    automatic: false,
    price: 32000,
    imageUrl: b,
    carType: 'SUV'
  },
  {
    id: 3,
    name: 'Chevrolet Cruze',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 450,
    automatic: true,
    price: 22000,
    imageUrl: c,
    carType: 'Sedan'
  },
  {
    id: 4,
    name: 'Dodge Charger',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 400,
    automatic: true,
    price: 25000,
    imageUrl: d,
    carType: 'Sedan'
  },
  {
    id: 5,
    name: 'Ford Mustang',
    yearProduced: 2023,
    occupants: 4,
    hybrid: true,
    distanceOnFullTank: 500,
    automatic: false,
    price: 32000,
    imageUrl: e,
    carType: 'Muscle'
  },
  {
    id: 6,
    name: 'Honda Civic',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 450,
    automatic: true,
    price: 22000,
    imageUrl: f,
    carType: 'Sedan'
  },
  {
    id: 7,
    name: 'Hyundai Sonata',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 400,
    automatic: true,
    price: 25000,
    imageUrl: g,
    carType: 'Sedan'
  },
  {
    id: 8,
    name: 'Kia Sportage',
    yearProduced: 2023,
    occupants: 4,
    hybrid: true,
    distanceOnFullTank: 500,
    automatic: false,
    price: 32000,
    imageUrl: h,
    carType: 'SUV'
  },
  {
    id: 9,
    name: 'Lexus RX 350',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 450,
    automatic: true,
    price: 22000,
    imageUrl: i,
    carType: 'SUV'
  },
  {
    id: 10,
    name: 'Mercedes-Benz E-Class',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 400,
    automatic: true,
    price: 25000,
    imageUrl: j,
    carType: 'Sedan'
  },
  {
    id: 11,
    name: 'Nissan Altima',
    yearProduced: 2023,
    occupants: 4,
    hybrid: true,
    distanceOnFullTank: 500,
    automatic: false,
    price: 32000,
    imageUrl: k,
    carType: 'Sedan'
  },
  {
    id: 12,
    name: 'Toyota Camry',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 450,
    automatic: true,
    price: 22000,
    imageUrl: l,
    carType: 'Sedan'
  },
  {
    id: 13,
    name: 'Volkswagen Passat',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 400,
    automatic: true,
    price: 25000,
    imageUrl: m,
    carType: 'Sedan'
  },
  {
    id: 14,
    name: 'Tesla Model 3',
    yearProduced: 2020,
    occupants: 4,
    hybrid: true,
    distanceOnFullTank: 500,
    automatic: true,
    price: 32000,
    imageUrl: n,
    carType: 'Electric'
  },
  {
    id: 15,
    name: 'Subaru Outback',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 450,
    automatic: true,
    price: 22000,
    imageUrl: o,
    carType: 'SUV'
  },
  {
    id: 16,
    name: 'Mazda CX-5',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 400,
    automatic: true,
    price: 25000,
    imageUrl: p,
    carType: 'SUV'
  },
  {
    id: 17,
    name: 'Jeep Grand Cherokee',
    yearProduced: 2023,
    occupants: 4,
    hybrid: true,
    distanceOnFullTank: 500,
    automatic: false,
    price: 32000,
    imageUrl: q,
    carType: 'SUV'
  },
  {
    id: 18,
    name: 'Fiat 500',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 450,
    automatic: true,
    price: 22000,
    imageUrl: r,
    carType: 'Compact'
  },
  {
    id: 19,
    name: 'Dodge Ram',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 400,
    automatic: true,
    price: 25000,
    imageUrl: s,
    carType: 'Truck'
  },
  {
    id: 20,
    name: 'Chrysler Pacifica',
    yearProduced: 2023,
    occupants: 4,
    hybrid: true,
    distanceOnFullTank: 500,
    automatic: false,
    price: 32000,
    imageUrl: t,
    carType: 'Minivan'
  },
  {
    id: 21,
    name: 'Lamborghini Huracan',
    yearProduced: 2021,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 350000,
    imageUrl: u,
    carType: 'Sports'
  },
  {
    id: 22,
    name: 'Ferrari 488 GTB',
    yearProduced: 2022,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 280000,
    imageUrl: v,
    carType: 'Sports'
  },
  {
    id: 23,
    name: 'Porsche 911',
    yearProduced: 2023,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 270000,
    imageUrl: w,
    carType: 'Sports'
  },
  {
    id: 24,
    name: 'McLaren 720S',
    yearProduced: 2021,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 350000,
    imageUrl: x,
    carType: 'Sports'
  },
  {
    id: 25,
    name: 'Bugatti Chiron',
    yearProduced: 2022,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 3000000,
    imageUrl: y,
    carType: 'Exotic'
  },
  {
    id: 26,
    name: 'Aston Martin Vantage',
    yearProduced: 2023,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 250000,
    imageUrl: z,
    carType: 'Exotic'
  },
  {
    id: 27,
    name: 'Rolls-Royce Ghost',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 400000,
    imageUrl: aa,
    carType: 'Luxury'
  },
  {
    id: 28,
    name: 'Lexus LX 570',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 90000,
    imageUrl: ab,
    carType: 'Luxury'
  },
  {
    id: 29,
    name: 'Land Rover Range Rover',
    yearProduced: 2023,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 95000,
    imageUrl: ac,
    carType: 'Luxury'
  },
  {
    id: 30,
    name: 'Toyota Land Cruiser',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 85000,
    imageUrl: ad,
    carType: 'SUV'
  },
  {
    id: 31,
    name: 'Subaru WRX',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 35000,
    imageUrl: ae,
    carType: 'Sedan'
  },
  {
    id: 32,
    name: 'Nissan 370Z',
    yearProduced: 2023,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 30000,
    imageUrl: af,
    carType: 'Sports'
  },
  {
    id: 33,
    name: 'Chevrolet Corvette',
    yearProduced: 2021,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 70000,
    imageUrl: ag,
    carType: 'Sports'
  },
  {
    id: 34,
    name: 'Dodge Challenger',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 45000,
    imageUrl: ah,
    carType: 'Muscle'
  },
  {
    id: 35,
    name: 'Ford F-150',
    yearProduced: 2023,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 40000,
    imageUrl: ai,
    carType: 'Truck'
  },
  {
    id: 36,
    name: 'GMC Sierra',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 45000,
    imageUrl: aj,
    carType: 'Truck'
  },
  {
    id: 37,
    name: 'Honda CR-V',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 35000,
    imageUrl: ak,
    carType: 'SUV'
  },
  {
    id: 38,
    name: 'Jeep Wrangler',
    yearProduced: 2023,
    occupants: 4,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 38000,
    imageUrl: al,
    carType: 'SUV'
  },
  {
    id: 39,
    name: 'Kia Sorento',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 32000,
    imageUrl: am,
    carType: 'SUV'
  },
  {
    id: 40,
    name: 'Lamborghini Aventador',
    yearProduced: 2022,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 450000,
    imageUrl: an,
    carType: 'Exotic'
  },
  {
    id: 41,
    name: 'Maserati Ghibli',
    yearProduced: 2023,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 75000,
    imageUrl: ao,
    carType: 'Luxury'
  },
  {
    id: 42,
    name: 'Nissan Rogue',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 33000,
    imageUrl: ap,
    carType: 'SUV'
  },
  {
    id: 43,
    name: 'Tesla Model X',
    yearProduced: 2022,
    occupants: 5,
    hybrid: true,
    distanceOnFullTank: 300,
    automatic: true,
    price: 60000,
    imageUrl: aq,
    carType: 'Electric'
  },
  {
    id: 44,
    name: 'Volkswagen Golf',
    yearProduced: 2023,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 28000,
    imageUrl: ar,
    carType: 'Compact'
  },
  {
    id: 45,
    name: 'Toyota RAV4',
    yearProduced: 2021,
    occupants: 5,
    hybrid: true,
    distanceOnFullTank: 300,
    automatic: true,
    price: 34000,
    imageUrl: as,
    carType: 'SUV'
  },
  {
    id: 46,
    name: 'Audi Q7',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 58000,
    imageUrl: at,
    carType: 'SUV'
  },
  {
    id: 47,
    name: 'BMW 3 Series',
    yearProduced: 2023,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 45000,
    imageUrl: au,
    carType: 'Sedan'
  },
  {
    id: 48,
    name: 'Chevrolet Silverado',
    yearProduced: 2021,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 40000,
    imageUrl: av,
    carType: 'Truck'
  },
  {
    id: 49,
    name: 'Dodge Dart',
    yearProduced: 2022,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 32000,
    imageUrl: aw,
    carType: 'Compact'
  },
  {
    id: 50,
    name: 'Ford Escape',
    yearProduced: 2023,
    occupants: 5,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 33000,
    imageUrl: ax,
    carType: 'SUV'
  },
  {
    id: 51,
    name: 'Nissan GT-R',
    yearProduced: 2022,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 300,
    automatic: true,
    price: 110000,
    imageUrl: ay,
    carType: 'Sports',
  },
  {
    id: 52,
    name: 'Koenigsegg Jesko',
    yearProduced: 2023,
    occupants: 2,
    hybrid: false,
    distanceOnFullTank: 250,
    automatic: true,
    price: 2800000,
    imageUrl: az,
    carType: 'Hypercar',
  },
    {
      id: 53,
      name: 'Porsche Cayenne',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 65000,
      imageUrl: ba,
      carType: 'SUV',
    },
    {
      id: 54,
      name: 'Jaguar F-Type',
      yearProduced: 2023,
      occupants: 2,
      hybrid: false,
      distanceOnFullTank: 300,
      automatic: true,
      price: 75000,
      imageUrl: bb,
      carType: 'Sports',
    },
    {
      id: 55,
      name: 'Audi Q5',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 52000,
      imageUrl: bc,
      carType: 'SUV',
    },
    {
      id: 56,
      name: 'BMW M4',
      yearProduced: 2023,
      occupants: 4,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 68000,
      imageUrl: bd,
      carType: 'Sports',
    },
    {
      id: 57,
      name: 'Lamborghini Urus',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 210000,
      imageUrl: be,
      carType: 'SUV',
    },
    {
      id: 58,
      name: 'Ferrari 812 Superfast',
      yearProduced: 2023,
      occupants: 2,
      hybrid: false,
      distanceOnFullTank: 250,
      automatic: true,
      price: 360000,
      imageUrl: bf,
      carType: 'Sports',
    },
    {
      id: 59,
      name: 'McLaren P1',
      yearProduced: 2022,
      occupants: 2,
      hybrid: false,
      distanceOnFullTank: 250,
      automatic: true,
      price: 1000000,
      imageUrl:bg,
      carType: 'Sports',
    },
    {
      id: 60,
      name: 'Kia Telluride',
      yearProduced: 2023,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 450,
      automatic: true,
      price: 42000,
      imageUrl: bh,
      carType: 'SUV',
    },
    {
      id: 61,
      name: 'Nissan Pathfinder',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 38000,
      imageUrl: bi,
      carType: 'SUV',
    },
    {
      id: 62,
      name: 'Toyota Highlander',
      yearProduced: 2023,
      occupants: 7,
      hybrid: true,
      distanceOnFullTank: 450,
      automatic: true,
      price: 43000,
      imageUrl: bj,
      carType: 'SUV',
    },
    {
      id: 63,
      name: 'Hyundai Santa Fe',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 32000,
      imageUrl: bk,
      carType: 'SUV',
    },
    {
      id: 64,
      name: 'Subaru Crosstrek',
      yearProduced: 2023,
      occupants: 5,
      hybrid: true,
      distanceOnFullTank: 400,
      automatic: true,
      price: 28000,
      imageUrl: bl,
      carType: 'SUV',
    },
    {
      id: 65,
      name: 'Mazda MX-5 Miata',
      yearProduced: 2022,
      occupants: 2,
      hybrid: false,
      distanceOnFullTank: 250,
      automatic: false,
      price: 27000,
      imageUrl: bm,
      carType: 'Sports',
    },
    {
      id: 66,
      name: 'Jeep Compass',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 25000,
      imageUrl: bn,
      carType: 'SUV',
    },
    {
      id: 67,
      name: 'Ford Explorer',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 45000,
      imageUrl: bo,
      carType: 'SUV',
    },
    {
      id: 68,
      name: 'Chevrolet Equinox',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 29000,
      imageUrl: bp,
      carType: 'SUV',
    },
    {
      id: 69,
      name: 'Dodge Durango',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 43000,
      imageUrl: bq,
      carType: 'SUV',
    },
    {
      id: 70,
      name: 'Volkswagen Tiguan',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 32000,
      imageUrl: br,
      carType: 'SUV',
    },
    {
      id: 71,
      name: 'Acura MDX',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 45000,
      imageUrl: bs,
      carType: 'SUV',
    },
    {
      id: 72,
      name: 'Buick Encore',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 28000,
      imageUrl: bt,
      carType: 'SUV',
    },
    {
      id: 73,
      name: 'Cadillac Escalade',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 75000,
      imageUrl: bu,
      carType: 'SUV',
    },
    {
      id: 74,
      name: 'GMC Yukon',
      yearProduced: 2023,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 72000,
      imageUrl: bv,
      carType: 'SUV',
    },
    {
      id: 75,
      name: 'Infiniti QX80',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 65000,
      imageUrl: bw,
      carType: 'SUV',
    },
    {
      id: 76,
      name: 'Lexus ES 350',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 48000,
      imageUrl: bx,
      carType: 'Sedan',
    },
    {
      id: 77,
      name: 'Lincoln Navigator',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 75000,
      imageUrl: by,
      carType: 'SUV',
    },
    {
      id: 78,
      name: 'Mercedes-Benz GLC',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 52000,
      imageUrl: bz,
      carType: 'SUV',
    },
    {
      id: 79,
      name: 'Tesla Model Y',
      yearProduced: 2022,
      occupants: 5,
      hybrid: true,
      distanceOnFullTank: 300,
      automatic: true,
      price: 54000,
      imageUrl: ca,
      carType:'Electric',
    },
    {
      id: 80,
      name: 'Volvo XC60',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 48000,
      imageUrl: cb,
      carType: 'SUV',
    },
    {
      id: 81,
      name: 'Audi Q8',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 58000,
      imageUrl: cc,
      carType: 'SUV',
    },
    {
      id: 82,
      name: 'BMW X3',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 53000,
      imageUrl: cd,
      carType: 'SUV',
    },
    {
      id: 83,
      name: 'Chevrolet Suburban',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 64000,
      imageUrl: ce,
      carType: 'SUV',
    },
    {
      id: 84,
      name: 'Dodge Journey',
      yearProduced: 2023,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 32000,
      imageUrl: cf,
      carType: 'SUV',
    },
    {
      id: 85,
      name: 'Ford Bronco',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 45000,
      imageUrl: cg,
      carType: 'SUV',
    },
    {
      id: 86,
      name: 'GMC Acadia',
      yearProduced: 2023,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 52000,
      imageUrl: ch,
      carType: 'SUV',
    },
    {
      id: 87,
      name: 'Honda Fit',
      yearProduced: 2022,
      occupants: 5,
      hybrid: true,
      distanceOnFullTank: 300,
      automatic: true,
      price: 22000,
      imageUrl: ci,
      carType: 'Hatchback',
    },
    {
      id: 88,
      name: 'Hyundai Tucson',
      yearProduced: 2023,
      occupants: 5,
      hybrid: true,
      distanceOnFullTank: 350,
      automatic: true,
      price: 28000,
      imageUrl: cj,
      carType: 'SUV',
    },
    {
      id: 89,
      name: 'Kia Soul',
      yearProduced: 2022,
      occupants: 5,
      hybrid: true,
      distanceOnFullTank: 300,
      automatic: true,
      price: 24000,
      imageUrl: ck,
      carType: 'Hatchback',
    },
    {
      id: 90,
      name: 'Lexus GX 460',
      yearProduced: 2023,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 55000,
      imageUrl: cl,
      carType: 'SUV',
    },
    {
      id: 91,
      name: 'Mazda3',
      yearProduced: 2022,
      occupants: 5,
      hybrid: true,
      distanceOnFullTank: 300,
      automatic: true,
      price: 26000,
      imageUrl: cm,
      carType: 'Sedan',
    },
    {
      id: 92,
      name: 'Nissan Murano',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 34000,
      imageUrl: cn,
      carType: 'SUV',
    },
    {
      id: 93,
      name: 'Subaru Forester',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 29000,
      imageUrl: co,
      carType: 'SUV',
    },
    {
      id: 94,
      name: 'Toyota Sienna',
      yearProduced: 2023,
      occupants: 7,
      hybrid: true,
      distanceOnFullTank: 300,
      automatic: true,
      price: 40000,
      imageUrl: cp,
      carType: 'Minivan',
    },
    {
      id: 95,
      name: 'Volkswagen Jetta',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 300,
      automatic: true,
      price: 23000,
      imageUrl: cq,
      carType: 'Sedan',
    },
    {
      id: 96,
      name: 'Volvo S60',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 300,
      automatic: true,
      price: 38000,
      imageUrl: cr,
      carType: 'Sedan',
    },
    {
      id: 97,
      name: 'Porsche Macan',
      yearProduced: 2022,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 62000,
      imageUrl: cs,
      carType: 'SUV',
    },
    {
      id: 98,
      name: 'Acura RDX',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 42000,
      imageUrl: ct,
      carType: 'SUV',
    },
    {
      id: 99,
      name: 'Buick Enclave',
      yearProduced: 2022,
      occupants: 7,
      hybrid: false,
      distanceOnFullTank: 400,
      automatic: true,
      price: 52000,
      imageUrl: cu,
      carType: 'SUV',
    },
    {
      id: 100,
      name: 'Cadillac XT5',
      yearProduced: 2023,
      occupants: 5,
      hybrid: false,
      distanceOnFullTank: 350,
      automatic: true,
      price: 48000,
      imageUrl: cv,
      carType: 'SUV',
    },
  ];
export default CarsData;
  